version: "3.8"

services:
  backend:
    build:
      context: .
    container_name: easeinterview_backend
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev --prefix Backend

  frontend:
    build:
      context: .
    container_name: easeinterview_frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start --prefix Frontend
